# This workflow uses actions to build and publish airflow image on a
# container registry.
name: Airflow
run-name: Publish Airflow Docker image
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  push_to_registry:
    name: Push Airflow Docker image to container registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: docker.registry
          username: dockeruser
          password: dockerpassword
      - name: Extract docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dockeruser/dockerimage
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/airflow/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
